//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace system_oceny.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Firmas> Firmas { get; set; }
        public virtual DbSet<Komentarzs> Komentarzs { get; set; }
        public virtual DbSet<Ocenas> Ocenas { get; set; }
        public virtual DbSet<Tranzakcjas> Tranzakcjas { get; set; }
        public virtual DbSet<Uzytkowniks> Uzytkowniks { get; set; }
        public virtual DbSet<Zdjecies> Zdjecies { get; set; }
    }
}
