//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace system_oceny.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkowniks
    {
        public Uzytkowniks()
        {
            this.Komentarzs = new HashSet<Komentarzs>();
            this.Ocenas = new HashSet<Ocenas>();
            this.Tranzakcjas = new HashSet<Tranzakcjas>();
        }
    
        public int uzytkownikId { get; set; }
    
        public virtual ICollection<Komentarzs> Komentarzs { get; set; }
        public virtual ICollection<Ocenas> Ocenas { get; set; }
        public virtual ICollection<Tranzakcjas> Tranzakcjas { get; set; }
    }
}
