//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace system_oceny.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zdjecies
    {
        public int zdjecieId { get; set; }
        public string opis { get; set; }
        public string sciezka { get; set; }
        public Nullable<int> Firma_Id { get; set; }
    
        public virtual Firmas Firmas { get; set; }
    }
}
